//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WhiteboxTestingPlatform.rc
//
#define ID_CONFIG                       3
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_WHITEBOXTESTINGPLATFORM_FORM 101
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_WhiteboxTestingTYPE         130
#define ID_WINDOW_MANAGER               131
#define IDS_WINDOWS_MANAGER             132
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define IDD_AUTOSTRUCTDATADESIGN_DIALOG 152
#define ID_PROPERTIES2                  153
#define IDR_HTML_USECASEEXPMAKEDLG      153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDS_PROJECT_VIEW                159
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define IDD_ExpMake                     180
#define ID_TOOLS_MACRO                  181
#define IDD_MAIN                        181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define IDR_OUTPUT_POPUP1               201
#define ID_VIEW_APPLOOK_WIN_2000        210
#define ID_VIEW_APPLOOK_OFF_XP          211
#define ID_VIEW_APPLOOK_WIN_XP          212
#define ID_VIEW_APPLOOK_OFF_2003        213
#define ID_VIEW_APPLOOK_VS_2005         214
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDD_TESTINGTASKVIEW             310
#define IDD_TESTINGTASKCONFIGVIEW       311
#define IDD_WORKSHEETVIEW               312
#define IDD_REPORTVIEW                  313
#define IDC_GRID                        314
#define IDR_HTML_NEWPOST                315
#define IDR_PROJECTVIEW_POPUP           317
#define IDD_TEST_WORKSHEET_VIEW         318
#define IDD_TESTUSER_REPORT_COMPLATE    319
#define IDD_TESTUSER_REPORT_COMPLATE_VIEW 319
#define IDD_TESTUSER_REPORT_MANUAL_MAKE_VIEW 320
#define IDD_TESTUSER_REPORT_NO_FIND_STANDARD_VIEW 321
#define IDD_TESTUSER_STANDARD_UNITE_VIEW 322
#define IDD_TESTUSER_STANDARD_THIRD_VIEW 323
#define IDD_TESTUSER_STANDARD_UNITE_EDIT 324
#define IDD_TESTUSER_STANDARD_UNITE_NEW 325
#define IDD_TESTUSER_STANDARD_THIRD_NEW 326
#define IDD_TESTUSER_STANDARD_THIRD_EDIT 327
#define IDD_DIALOG1                     328
#define IDD_DLG_CREATE_PROJECT          328
#define IDR_STANDARD_MENU               328
#define IDD_TESTUSER_STANDARD_NEW       329
#define IDD_STANDARD_FIELD_EDIT         332
#define IDD_ADMINUSER_USEREDIT_VIEW     333
#define IDD_ADMINUSER_USERADDEDIT_DLG   334
#define IDD_LOGONIN_DLG                 335
#define IDD_CONFIG                      336
#define IDD_FLOATWND                    337
#define IDD_DEVUSER_REPORT_VIEW         338
#define IDB_BITMAP_OK                   341
#define IDR_ACCELERATOR1                345
#define IDR_OBJECT_LOCK_MENU            348
#define IDD_DEVUSER_REPORT_VIEW_2       349
#define IDD_DEVUSER_REPORT_VIEW_1       350
#define IDD_DIALOG2                     353
#define IDD_CODEVIEW_DLG                353
#define IDD_NEWPOST                     354
#define IDD_SUBPROJECTMANGERDLG         355
#define IDD_ADDR_NAVIGATE               356
#define IDD_CODEVIEW                    357
#define IDD_MSGSHOW_VIEW                358
#define IDD_UNIT_TEST_AUTOREPORT        359
#define IDD_UNITADDEDIT                 360
#define IDD_UNIT_ENDTime                361
#define IDD_STRCUTDATA_DESIGN_VIEW      362
#define IDD_NEWEXPDLG                   365
#define IDD_DIALOG3                     366
#define IDD_TESTLIBMGR                  366
#define IDD_MACRO                       367
#define IDC_LIST1                       1000
#define IDC_EDIT1                       1001
#define IDC_EDIT2                       1002
#define IDC_EDIT3                       1003
#define IDC_LIST_MACRO_FUNC             1003
#define IDC_EDIT4                       1004
#define IDC_LIST_MACRO_FUNC_CLOSE       1004
#define IDC_EDIT5                       1005
#define IDC_EDIT6                       1006
#define IDC_EDIT7                       1007
#define IDC_RADIO1                      1008
#define IDC_EDIT14                      1008
#define IDC_RADIO2                      1009
#define IDC_EDIT8                       1010
#define IDC_EDIT9                       1011
#define IDC_EDIT10                      1012
#define IDC_RADIO_CHECKRESULT1          1012
#define IDC_RADIO_CHECKRESULT_SUCC      1012
#define IDC_EDIT_BT                     1012
#define IDC_EDIT12                      1013
#define IDC_EDIT_BT2                    1013
#define IDC_EDIT13                      1014
#define IDC_RADIO_CHECKRESULT2          1014
#define IDC_RADIO_CHECKRESULT_FAIL      1014
#define IDC_EDIT11                      1015
#define IDC_EDIT_CHECKRESULT_DES        1015
#define IDC_BUTTON1                     1016
#define IDC_BUTTON2                     1017
#define IDC_DELETE_CUR                  1017
#define IDC_REMOVE                      1017
#define IDC_BUTTON266                   1017
#define IDC_ERRORTYPE_DELETE            1017
#define IDC_ADDPRO                      1017
#define IDC_CANCAL                      1017
#define IDC_DelTemplate                 1017
#define IDC_NEWTESTLIB                  1017
#define IDC_LOOKTHIRD                   1018
#define IDC_ERRCLASS_DELETE             1018
#define IDC_REMOVEPRO                   1018
#define IDC_AutoMake                    1018
#define IDC_UpData                      1018
#define IDC_COMBO1                      1019
#define IDC_LOOKTHIRD2                  1019
#define IDC_SUBMIT                      1019
#define IDC_DelTemplate2                1019
#define IDC_COMBO2                      1020
#define IDC_REFRESH                     1020
#define IDC_UpData2                     1020
#define IDC_LIST_REPORT                 1021
#define IDC_ERROR_NUM                   1022
#define IDC_ADD                         1022
#define IDC_SENDPOST                    1022
#define IDC_SUBMIT2                     1022
#define IDC_LOOKTHIRD3                  1022
#define IDC_DELSELIG                    1022
#define IDC_ERROR_NUM_THIRD             1023
#define IDC_ERROR_NUM2                  1023
#define IDC_REPORT_LIST                 1024
#define IDC_ERROR_NUM_UNITE             1024
#define IDC_ERROR_NUM_THIRD2            1024
#define IDC_LINE_NUM                    1025
#define IDC_ERROR_NUM3                  1025
#define IDC_EDITREPORT                  1025
#define IDC_EDITPOST                    1025
#define IDC_FILENAME                    1026
#define IDC_ERROR_NUM4                  1026
#define IDC_ERROR_UNITENUM              1026
#define IDC_DELREPORT                   1026
#define IDC_DESCRIPTION                 1027
#define IDC_ERROR_NUM5                  1027
#define IDC_COMPLATE_CUR_REPORT         1028
#define IDC_DESCRIPTION2                1028
#define IDC_COMPLATE_REPORT             1028
#define IDC_EDIT_THIRD                  1029
#define IDC_DESCRIPTION3                1029
#define IDC_COMBO3                      1029
#define IDC_COMBO_ERROR_CLASS           1029
#define IDC_COMBO_PRARMTYPE             1029
#define IDC_COMBO4                      1030
#define IDC_REBUILD_CUR                 1030
#define IDC_DESCRIPTION4                1030
#define IDC_ERROR_NUM_THIRD4            1030
#define IDC_COMPLATE_CUR_REPORT2        1030
#define IDC_IGNORE_CUR_REPORT           1030
#define IDC_COMBO_PRARMTYPE2            1030
#define IDC_NEW_STANDARD                1031
#define IDC_NEW_STANDARD2               1032
#define IDC_NEW                         1032
#define IDC_COMPLATE_STANDARD           1033
#define IDC_CANCEL                      1033
#define IDC_MODIFY                      1034
#define IDC_DESCRIPTION5                1034
#define IDC_CHECK1                      1035
#define IDC_CHECK_ISCOPYLIB             1035
#define IDC_CHECK2                      1036
#define IDC_LIST2                       1036
#define IDC_LIST_USER                   1036
#define IDC_TEMPLATE_LIST               1036
#define IDC_ADD_THIRD_TO_USINGLIST      1037
#define IDC_PRARM_LIST                  1037
#define IDC_OK                          1038
#define IDC_CHECK3                      1039
#define IDC_ERROR_NOCHECK               1039
#define IDC_LIST_NOUSING                1039
#define IDC_EDITUSER                    1039
#define IDC_ADDUSER                     1040
#define IDC_EDIT_NAME                   1041
#define IDC_DELSELUSER                  1041
#define IDC_UINTE_STANDARD_LIST         1042
#define IDC_EDIT_STANDARD               1044
#define IDC_ERROR_TYPE                  1045
#define IDC_ERROR_CLASS                 1046
#define IDC_ERROR_DESC                  1047
#define IDC_ERROR_SUG                   1048
#define IDC_BUTTON3                     1049
#define IDC_COMBO_SPECIFYNAME           1050
#define IDC_DERROR_TYPE                 1050
#define IDC_ERROR_WA                    1051
#define IDC_STATIC_SUBPROJECT_NAME      1052
#define IDC_STATIC_SUBPROJECT_NAME2     1053
#define IDC_STATIC_CMDPARAM             1053
#define IDC_ERROR_MANUAL                1053
#define IDC_ERROR_CHECKSUG              1054
#define IDC_ERROR_TOOLTYPE              1056
#define IDC_COMBO_TOOLTYPE              1057
#define IDC_EDIT_STANDARDPARAM          1058
#define IDC_ERROR_MANUAL_SUG            1059
#define IDC_EDIT_STANDARDPARAM2         1059
#define IDC_EDIT_PRIVATEPARAM           1059
#define IDC_COMBO_ERROR_TYPE            1060
#define IDC_COMBO_ERROR_CLAS            1061
#define IDC_COMBO_ERROR_CLASS1          1061
#define IDC_LIST_USING                  1062
#define IDC_STATIC_BASE                 1063
#define IDC_EDIT_SUGGEST                1064
#define IDC_ERROR_TYPE_LIST             1065
#define IDC_ERRTYPE_ADD                 1066
#define IDC_ERROR_CLASS_LIST            1067
#define IDC_ERRCLASS_ADD                1068
#define IDC_ERRORTYPE                   1069
#define IDC_ERRORWRANING                1070
#define IDC_EDIT_SUGGEST_ADD            1071
#define IDC_EDIT_CHECK_MEMO             1071
#define IDC_ERROR_DESCRIPTION           1073
#define IDC_LIST_USERPROJECT            1074
#define IDC_USERNAME                    1075
#define IDC_LIST_NOUSING_USERPROJECT    1075
#define IDC_PASSWORD                    1076
#define IDC_REPASSWORD                  1077
#define IDC_COMBO_USERTYPE              1078
#define IDC_COMBO_LOGON_TYPE            1079
#define IDC_EDIT_USERNAME               1080
#define IDC_EDIT_PASSWORD               1081
#define IDC_LOCALDIR                    1082
#define IDC_COMBO_LOGON_APP_TYPE        1082
#define IDC_SOAPDIR                     1083
#define IDC_SOAPTIMEOUT                 1084
#define IDC_MAKE_SUMMARY                1085
#define IDC_STATIC_GIF                  1088
#define IDC_EDIT_SOURCELIST             1088
#define IDC_STATIC_TIP                  1089
#define IDC_STATIC_TIP2                 1089
#define IDC_DATE_CHECK                  1089
#define IDC_DATE_APPLY                  1090
#define IDC_EDIT_PROJECTNO              1091
#define IDC_EDIT_WORKNO                 1092
#define IDC_EDIT_MODULENO               1093
#define IDC_COMBO_CHECKRANGE            1094
#define IDC_EDIT_APPLY                  1095
#define IDC_EDIT_CHECKMAN_LIST          1096
#define IDC_RADIO_CHECKTYPE1            1097
#define IDC_RADIO_CHECKTYPE_ADD         1097
#define IDC_RADIO_CHECKTYPE2            1098
#define IDC_RADIO_CHECKTYPE_ALL         1098
#define IDC_EDIT_PREWORKNO              1099
#define IDC_EDIT_SVNPATH                1100
#define IDC_EDIT_CHECKMAN               1101
#define IDC_BUTTON_SAVE                 1102
#define IDC_COMBO_DEVSTATE              1103
#define IDC_EDIT_FEEDBACK               1104
#define IDC_TAB_DATA                    1105
#define IDC_EDIT_FEEDBACK_ADD           1105
#define IDC_COMBO_CHECKRANGE2           1105
#define IDC_COMBO_APPLY                 1105
#define IDC_COMBO_DEVSTATE3             1106
#define IDC_COMBO_DISPATCH              1106
#define IDC_EDIT_SUBJECT                1106
#define IDC_EDIT_POSITION               1107
#define IDC_EDIT_SUBJECT2               1108
#define IDC_EDIT_CONTENT                1108
#define IDC_COMBO_PROJECTSTATE          1108
#define IDC_COMBO_ADDRTYPE              1109
#define IDC_ADDR                        1110
#define IDC_EDIT                        1111
#define IDC_UnitList                    1112
#define IDC_EDIT_IVT                    1113
#define IDC_COPYSEL                     1113
#define IDC_EDIT_INVT                   1114
#define IDC_DELSEL                      1114
#define IDC_EDIT_RCT                    1115
#define IDC_EDIT_TCCDT                  1116
#define IDC_EDIT_PRJNAME                1117
#define IDC_EDIT_SYSNAME                1118
#define IDC_EDIT_MODULENAME             1119
#define IDC_EDIT_TESTER                 1120
#define IDC_EDIT_JUDGE                  1121
#define IDC_EDIT_SUG                    1123
#define IDC_EDIT_IVT2                   1124
#define IDC_EDIT_INVT2                  1125
#define IDC_EDIT_TCCDT2                 1126
#define IDC_EDIT_RCT2                   1127
#define IDC_DATE_JUDGEDATE              1128
#define IDC_DATE_TESTDATE               1129
#define IDC_DATETIMEPICKER1             1129
#define IDC_TYPE_TYPE                   1130
#define IDC_AddTemplate                 1131
#define IDC_DESC                        1132
#define IDC_PARAMNAME                   1133
#define IDC_PARAMNAME2                  1134
#define IDC_LIST_TESTLIB                1134
#define IDC_DESC2                       1135
#define IDC_DELLIB                      1135
#define IDC_AddToTypeLib                1136
#define IDC_BUTTON_LOADLIB              1136
#define IDC_SAVE                        1137
#define IDC_STATIC_DESC                 1137
#define IDC_PARAMNAME3                  1138
#define IDC_AddTemplate3                1139
#define IDC_UP                          1139
#define IDC_LEFT                        1140
#define IDC_RIGHT                       1141
#define IDC_DOWN                        1142
#define IDC_LIST_MACRO                  1143
#define IDC_LIST_PRARMDEF_CLOSE         1144
#define IDC_EDIT_MACRONAME              1145
#define IDC_COMBO_MACROTYPE             1146
#define IDC_LEFT_PAR                    1148
#define IDC_RIGHT_PAR                   1149
#define IDC_LIST_FUNC                   1500
#define IDC_EDIT_PARAMNAME              1501
#define IDC_EDIT_DESC                   1502
#define IDC_LIST_PRARMDEF               1503
#define IDC_ADDFUNC                     1504
#define IDC_DELFUNC                     1505
#define IDC_ADDPRRARM                   1506
#define IDC_DELPARAM                    1507
#define IDC_UPDATA_PARAMDEF             1508
#define IDC_EDIT_DEFAULTPARAM           1509
#define IDC_LIST_FUNC2                  1510
#define IDC_LIST_EXP                    1510
#define IDC_EDITFUNC                    1510
#define IDC_EDIT_PARAMNAME3             1511
#define IDC_LIST_PRARM2                 1512
#define IDC_UPDATA_PARAM2               1513
#define IDC_EDIT_PARAMNAME2             1514
#define IDC_EDIT_FUNCDESC               1515
#define IDC_ADDCASEEXP                  1517
#define IDC_DELCASEEXP                  1518
#define IDC_RunSel                      1519
#define IDC_RunAll                      1520
#define IDC_EDIT_USECASENAME            1520
#define IDC_EDIT_USECASEDESC            1521
#define IDC_COMBO_ENUMEXP               1522
#define IDC_TAB1                        1523
#define ID_BUILD                        32775
#define ID_BUILD_REPORT                 32776
#define ID_CREATE_TASK                  32777
#define ID_Menu                         32778
#define ID_CREATE_PROJECT               32779
#define ID_REBUILD_REPORT               32780
#define ID_32781                        32781
#define ID_TEST_32782                   32782
#define ID_TEST_32783                   32783
#define ID_TEST_001                     32784
#define ID_TEST002                      32785
#define ID_TEST_002                     32786
#define ID_TEST_3                       32787
#define ID_TEST_4                       32788
#define ID_TEST_5                       32789
#define ID_TEST_6                       32790
#define ID_TEST_7                       32791
#define ID_TEST_8                       32792
#define ID_TEST_9                       32793
#define ID_TEST_10                      32794
#define ID_TEST_003                     32795
#define ID_TEST_004                     32796
#define ID_TEST_005                     32797
#define ID_TEST_006                     32798
#define ID_TEST_007                     32799
#define ID_TEST_008                     32800
#define ID_TEST_009                     32801
#define ID_TEST_010                     32802
#define ID_REPORT_REFRESH               32803
#define ID_32804                        32804
#define ID_Menu32805                    32805
#define ID_STANDARD_MENU_NEW            32806
#define ID_STANDARD_MENU_UPDATA         32807
#define ID_32808                        32808
#define ID_STANDARD_MENU_DELETE         32809
#define ID_PROJECTVIEW_DEL              32812
#define ID_32813                        32813
#define ID_STOP_BUILD                   32814
#define ID_32815                        32815
#define ID_STANDARD_MENU_REGET          32816
#define ID_32817                        32817
#define ID_REPORT_REGET                 32818
#define ID_BUTTON32820                  32820
#define ID_BUTTON32821                  32821
#define ID_BUTTON32822                  32822
#define ID_BUTTON32823                  32823
#define ID_RELEASE_LOCK                 32826
#define ID_OBJ_REGET                    32827
#define ID_OBJ_RELEASE_LOCK             32828
#define ID_OBJ_GETLOCK                  32829
#define ID_CREATE_DIRECTORY             32830
#define ID_PROJECTVIEW_REGET            32831
#define ID_PROJECT_UNLOCK               32832
#define ID_PROJECTTREE_REGET            32833
#define ID_PROJECT                      32833
#define ID_PROJECT_MANGER               32834
#define ID_GET_NODEPATH                 32835

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        368
#define _APS_NEXT_COMMAND_VALUE         32836
#define _APS_NEXT_CONTROL_VALUE         1147
#define _APS_NEXT_SYMED_VALUE           316
#endif
#endif
